name: Build DEB Package

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git perl libssl-dev clang
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          
          # Xoá thư mục sdks mặc định và clone kho SDK mới
          rm -rf $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks

      - name: Build Tweak
        run: |
          export THEOS=$HOME/theos
          $THEOS/bin/make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MUHelperPatch-DEB
          path: packages/*.deb
